image:
  repository: "fluent/fluentd-kubernetes-daemonset"
  tag: "v1.14.5-debian-opensearch-amd64-1.0"
  pullPolicy: IfNotPresent

resources: {}
   limits:
     cpu: 100m
     memory: 200Mi
   requests:
     cpu: 100m
     memory: 150Mi

serviceAccount:
  create: true
  annotations: {}
  name: fluentd

rbac:
  create: true
  rules:
  verbs:
    - get
    - list
    - watch
  apiGroups:
    - ''
  resources:
    - nodes
    - pods
    - namespaces

env:
# hosts https://user:pass@ES_HOST_URL:443
#- name: FLUENT_ELASTICSEARCH_HOST
#  value: "https://user:pass@ES_HOST_URL:443"
- name: FLUENT_ELASTICSEARCH_HOST
  value: "ES_HOST_URL:443"
- name: FLUENT_ELASTICSEARCH_PORT
  value: "9200"
- name: FLUENT_ELASTICSEARCH_SCHEME
  value: "https"
- name: "FLUENTD_CONF"
  value: "./fluent.conf"

volumeMounts:
- name: varlog
  mountPath: /var/log
- name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
  readOnly: true
- name: config-path
  mountPath: /fluentd/etc
  terminationGracePeriodSeconds: 30
volumes:
- name: varlog
  hostPath:
  path: /var/log
- name: varlibdockercontainers
  hostPath:
  path: /var/lib/docker/containers
- name: config-source
  configMap:
  name: fluentdconf
- name: config-path
  emptyDir: {}